# -*- coding: utf-8 -*-
"""Rateio de energia v2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W60ChHFTr_lw2aGyNjjMPwaFQOlxL3SA
"""

import streamlit as st
import pandas as pd
from datetime import datetime
import io

# -----------------------------
# CONFIGURAÇÕES DE TARIFAS FIXAS
# -----------------------------
tarifas = {
    'te_ate_150': 0.392200,
    'te_acima_150': 0.415851,
    'tusd_ate_150': 0.455333,
    'tusd_acima_150': 0.482660,
    'icms_ate_150': 0.12,
    'icms_acima_150': 0.17,
    'cosip': 17.01
}

bandeiras = {
    "verde": 0.00000,
    "amarela": 0.01866,
    "vermelha1": 0.04463,
    "vermelha2": 0.08777
}

# -----------------------------
# FUNÇÕES
# -----------------------------
def calcular_valor_consumo(consumo, tarifas, bandeira):
    consumo_1 = min(consumo, 150)
    consumo_2 = max(consumo - 150, 0)

    valor_te = (consumo_1 * tarifas['te_ate_150']) + (consumo_2 * tarifas['te_acima_150'])
    valor_tusd = (consumo_1 * tarifas['tusd_ate_150']) + (consumo_2 * tarifas['tusd_acima_150'])
    valor_bandeira = consumo * bandeiras[bandeira]

    icms_1 = (consumo_1 * (tarifas['te_ate_150'] + tarifas['tusd_ate_150'])) * tarifas['icms_ate_150']
    icms_2 = (consumo_2 * (tarifas['te_acima_150'] + tarifas['tusd_acima_150'])) * tarifas['icms_acima_150']

    total = valor_te + valor_tusd + valor_bandeira + icms_1 + icms_2
    return round(total, 2)

def calcular_fatura_total(leitura_anterior, leitura_atual, tarifas, bandeira):
    consumo_total = leitura_atual - leitura_anterior
    valor_total = calcular_valor_consumo(consumo_total, tarifas, bandeira) + tarifas['cosip']
    return round(valor_total, 2), consumo_total

# -----------------------------
# INTERFACE STREAMLIT
# -----------------------------
st.title("💡 Rateio de Energia - Quitinetes")

# Entradas principais em colunas
col1, col2 = st.columns(2)
with col1:
    leitura_anterior = st.number_input("Leitura anterior do prédio", min_value=0, step=1)
with col2:
    leitura_atual = st.number_input("Leitura atual do prédio", min_value=0, step=1)

bandeira = st.radio("Bandeira vigente", ["verde", "amarela", "vermelha1", "vermelha2"])
n = st.slider("Número de quitinetes", 1, 20)

consumos_individuais = []
valores_individuais = []

for i in range(n):
    st.subheader(f"Quitinete {i+1}")
    colA, colB = st.columns(2)
    with colA:
        leitura_ant = st.number_input(f"Leitura anterior Q{i+1}", min_value=0, step=1, key=f"ant_{i}")
    with colB:
        leitura_at = st.number_input(f"Leitura atual Q{i+1}", min_value=0, step=1, key=f"at_{i}")
    consumo = leitura_at - leitura_ant
    consumos_individuais.append(consumo)
    valores_individuais.append(calcular_valor_consumo(consumo, tarifas, bandeira))

# Botão de cálculo
if st.button("Calcular"):
    valor_total, consumo_total = calcular_fatura_total(leitura_anterior, leitura_atual, tarifas, bandeira)
    soma_individuais = sum(consumos_individuais)
    saldo_consumo = consumo_total - soma_individuais
    saldo_valor = round(valor_total - sum(valores_individuais), 2)

    # Monta DataFrame
    dados = {
        "Consumo (kWh)": consumos_individuais + [saldo_consumo],
        "Valor (R$)": valores_individuais + [saldo_valor]
    }
    df = pd.DataFrame(dados, index=[f"Quitinete {i+1}" for i in range(n)] + ["Áreas Comuns"])

    st.success(f"Consumo total do prédio: {consumo_total} kWh")
    st.success(f"Valor total da fatura: R$ {valor_total}")

    # Exibe tabela
    st.subheader("📊 Rateio detalhado")
    st.table(df)

    # Gráfico de barras
    st.subheader("📈 Consumo por unidade")
    st.bar_chart(df["Consumo (kWh)"])

    # Botão de download direto
    buffer = io.BytesIO()
    df.to_excel(buffer, index=True)
    buffer.seek(0)
    st.download_button(
        label="⬇️ Baixar relatório em Excel",
        data=buffer,
        file_name=f"rateio_{datetime.now().strftime('%m_%Y')}.xlsx",
        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )